language: c
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=2.7
    - os: linux
      env: PYTHON_VERSION=2.7 USE_OBSPYH5="true"
    - os: linux
      env: PYTHON_VERSION=3.5 USE_OBSPYH5="true"
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.6 USE_OBSPYH5="true"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX";
    else
      OS="Linux";
    fi
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - if [[ $USE_OBSPYH5 == "true" ]]; then
      OBSPYH5DEP="cython h5py"; OBSPYH5="obspyh5";
    else
      OBSPYH5DEP=""; OBSPYH5="";
    fi
# explicitely specify scipy because of https://github.com/conda/conda/issues/6199
  - conda create -q -n testenv
      python=$PYTHON_VERSION
      obspy gcc coverage
      tqdm shapely cartopy
      geographiclib
      scipy
      $OBSPYH5DEP
  - source activate testenv
  - pip install toeplitz $OBSPYH5
  - conda list
install:
  - pip install --no-deps .
script:
  - mkdir empty; cd empty
  - coverage run --include='*/rf/*' -m rf.tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
