language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-setuptools python-numpy python-scipy python-matplotlib python-lxml python-sqlalchemy python-suds gfortran
  - pip install toeplitz geographiclib
  - pip install --allow-external obspy --allow-insecure obspy obspy==dev

install:
  - pip install .
script:
  - rf-runtests
after_success:
notifications:
    email: false