language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-setuptools python-numpy python-scipy python-matplotlib python-lxml python-sqlalchemy python-suds gfortran
  - pip install toeplitz geographiclib
  # Future 0.11.3 has some issues and essentially does not work under Python 2.x. Older
  # versions have some other issues. The master more or less resolves them.
  # XXX: Replace once a new future version has been released!
  - pip install https://github.com/PythonCharmers/python-future/archive/master.zip
  # XXX: At the moment rf is working only with obspy master
  - pip install --allow-external obspy --allow-insecure obspy obspy==dev
  - pip freeze

install:
  - pip install .
script:
  - rf-runtests
after_success:
notifications:
    email: false