language: python
python:
  - "2.7"
env:
  -
  - USE_OBSPYH5=true
sudo: false
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"  
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
  - conda install python=$TRAVIS_PYTHON_VERSION gcc coverage
  - conda install -c obspy obspy
  - conda install -c conda-forge shapely cartopy
  - pip install toeplitz geographiclib
  - if [[ $USE_OBSPYH5 == true ]]; then conda install python=$TRAVIS_PYTHON_VERSION cython h5py; pip install obspyh5; fi  
install:
  - pip install .
script:
  - mkdir empty; cd empty  
  - coverage run --include='*/rf/*' --omit='*/tests/*' -m rf.tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
