language: c
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.7
    - os: linux
      env: PYTHON_VERSION=3.7 USE_OBSPYH5="true"
    - os: osx
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.7 USE_OBSPYH5="true"
    - os: windows
      env: PYTHON_VERSION=3.7 USE_OBSPYH5="true"
before_install:
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      GF="gfortran_osx-64"; TOEPLITZ="toeplitz";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      GF="gfortran_linux-64"; TOEPLITZ="toeplitz";
    fi
  - if [[ $USE_OBSPYH5 == "true" ]]; then
      OBSPYH5DEP="h5py"; OBSPYH5="obspyh5";
    fi
  - # fix for taupy fails, see Obspy #2319, can be removed at a later point
  - if [[ $PYTHON_VERSION == 3.7 ]]; then
      OBSPYVERSION=">=1.1.1";
    fi
  - conda config --add channels conda-forge
  - conda create -q -n testenv
      python=$PYTHON_VERSION
      decorator matplotlib numpy scipy "obspy$OBSPYVERSION"
      tqdm shapely cartopy geographiclib
      $GF $OBSPYH5DEP
      coverage
  - conda activate testenv
  - pip install $TOEPLITZ $OBSPYH5
  - conda list
install:
  - pip install -v --no-deps .
script:
  - mkdir empty; cd empty
  - coverage run --include='*/rf/*' -m rf.tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
