name: tests
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.6, 3.7, 3.8]
        add_package: [""]
        include:
          - os: macos-latest
            python: 3.8
          - os: windows-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.8
            add_package: obspyh5_toeplitz
          - os: macos-latest
            python: 3.8
            add_package: obspyh5_toeplitz
          - os: windows-latest
            python: 3.8
            add_package: obspyh5_toeplitz
    env:
      add_package: ${{ matrix.add_package }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          environment-file: .github/test_conda_env.yml
      - name: print conda environment info
        run: |
          conda info -a
          conda list
      - name: install optional dependencies
        run: |
          if [[ $add_package == "obspyh5_toeplitz" ]]; then
            conda install h5py fortran-compiler;
            pip install obspyh5 toeplitz;
          fi
      - name: install package
        run: |
          pip install -v --no-deps .
          conda list
      - name: run test suite
        run: |
          mkdir empty; cd empty
          coverage run --include='*/rf/*' -m rf.tests
          coverage xml -o ../coverage.xml
      - name: upload coverage
        uses: codecov/codecov-action@v1
